### PR TITLE
 #[161382400]:Users should be able to favorite articles

### PR DESCRIPTION
**Pull request by johnkegz**
#### What does this PR do?
Compares develop with ft-favourite-article-161382400
#### Description of Task to be completed?
users should be able to favorite and or unfavorite articles.
#### How should this be manually tested?
In swagger, insert a slug of the article you want to favorite for the favorite post endpoint
screen shot 2018-11-13 at 18 41 32
screen shot 2018-11-13 at 18 41 48
For unfavoriting, Insert the slug of the article you want to unfavorite and press execute
screen shot 2018-11-13 at 18 42 12
screen shot 2018-11-13 at 18 42 27

#### Any background context you want to provide?
Articles that tickle our fancy are worth favoriting and those deemed distasteful are worth unfavoriting.
#### What are the relevant pivotal tracker stories?
#161382400

### CODE REVIEW

**Comment by malep2007** [comment]
Fix merge conflicts @johnkegz

**Comment by johnkegz** [comment]
@malep2007 I have fixed the conflicts

**Comment by emukungu** [comment]
All checks are passing, looks good

**Review by joshNic — APPROVED** [review]
@johnkegz this is good work I see you are following the naming conversions that were agreed upon but improve on the line length and also the line spacing so that it conforms to the PEP8 standards, otherwise, this is good stuff

**Review by bozicschucky — APPROVED** [review]
You have followed the conventions and it looks good to me.
Please on the next PR remove the extra white spaces included in your changes.

**Comment by johnkegz** [comment]
@joshNic @bozicschucky I have formatted the files using auto pep8 and the white space issue has been resolved. Please review

**Review by joshNic — APPROVED** [review]
The code is now fine, I see that you have fixed what was pointed out. This is good stuff

**Review by malep2007 — COMMENTED** [review]
Looks good to me

**Pull request merged**
