### PR TITLE
#161382389 Users should receive a JWT on successful Registration

### PR DESCRIPTION
**Pull request by cdvx**
#### What does this PR do?
Users can recieve JWT tokens upon login
#### Description of Task to be completed?
when user logs in via `api/users/login/`
users recieves a `token` which then can use to access protected features
#### How should this be manually tested?
run server with `python manage.py runserver`
in `postman` sign up a user with object of this format

          { "user": {
                "username": "kegz",
                "email": "kegz@gmail.com",
                "password": "1231234567"
            }
        }

- then login the user with object of format

          { "user": {
                "email": "kegz@gmail.com",
                "password": "1231234567"
            }
        }

- one should also use the following headers

`Content-Type` ==> `Application/Json`
`Authorization` ==> `Token ` + `actual token`

#### Any background context you want to provide?
to test this, one `should` have `PostgreSQL` installed locally and should clone  the repository with

`git clone https://github.com/andela/ah-backend-thor.git`

then create a database called `ah-backend`

make and run migrations
`python manage.py makemigrations`
`python manage.py migrate`

#### What are the relevant pivotal tracker stories?
#161382389

### CODE REVIEW

**Review by malep2007 — CHANGES_REQUESTED** [review]
- [ ] @cdvx in the ```JWTAuthentication ``` class in the backends.py file, the ```authenticate``` method could do with some refactoring. especially the if statements.
- [ ] Also, by now I expect a new line at the end of each file.

**Comment by emukungu** [comment]
Good coverage

**Review by malep2007 — CHANGES_REQUESTED** [review]
- @cdvx add a new line to .coveragerc file, travis.yml, or any file that you touched. TIP: use an editor config to help you do this automatically every time you save changes while coding.

**Review by malep2007 — APPROVED** [review]

**Comment by malep2007** [comment]
@cdvx Looks ok to me

**Pull request merged**
