### PR TITLE
#161382387 add swagger (Api Documentation)

### PR DESCRIPTION
**Pull request by joshNic**
#### What does this PR do?
Documents API using swagger
#### Description of Task to be completed?
- install the Django REST Swagger package which is a documentation Generator for Django REST Framework
- Add rest_framework_swagger on the list of installed apps
- Add schema view to the urls.py
#### How should this be manually tested?
- Run python manage.py
- Navigate to the browser then in the url type http://127.0.0.1:8000
#### Any background context you want to provide?

- When creating APIs, Swagger tooling may be used to automatically generate an Open API document based on the code itself.
This is informally called code-first or bottom-up API development.
- This swagger allows connections directly to live APIs through an interactive, HTML-based user interface.
- Requests can be made directly from the UI and the options explored by the user of the interface.
#### What are the relevant pivotal tracker stories?
#161382387

### CODE REVIEW

**Comment by emukungu** [comment]
@joshNic 
You have a commit message of update README, adds swagger,...
You have 3 commits, I was expecting one commit in the pull request

**Comment by malep2007** [comment]
@joshNic, could you update your PR comment to include a brief way in which we can know that swagger works?

**Comment by malep2007** [comment]
Please squash your commits to one, this one -> [Started ft #161382387] adds swagger

**Comment by cdvx** [comment]
@joshNic 
Fix merge conflicts

**Comment by bozicschucky** [comment]
Looks good to me.

**Pull request merged**
