### PR TITLE
Ch descriptive validation errors 161382390

### PR DESCRIPTION
**Pull request by bozicschucky**
#### Description of Task to be completed?
Adding Descriptive error messages and user registeration validation
#### How should this be manually tested?
- Git clone this branch.
- Pip install requirements.txt
- Python manage.py run server
- Got the documentation version of the app
- Test the user endpoints using postman or the documentation.
#### Any background context you want to provide?
-Try testing the user inputs by providing invalid data.
- Run the tests to see how the different parts of tested
#### What are the relevant pivotal tracker stories?
161382390

### CODE REVIEW

**Comment by cdvx** [comment]
@bozicschucky Good stuff! Looks good, you improved the tests and cleaned up some code. 53 commits however,  you may need to squash

**Review by malep2007 — CHANGES_REQUESTED** [review]
@bozicschucky thanks for the good work. Could you, however, squash the commits to one. It will not be possible for me to merge your work with all these commits

**Review by malep2007 — APPROVED** [review]

**Review by malep2007 — CHANGES_REQUESTED** [review]
@chucky, there are some merge conflicts. Could resolve them?

**Review by johnkegz — APPROVED** [review]

**Review by malep2007 — APPROVED** [review]

**Comment by malep2007** [comment]
@bozicschucky Looks good to me.

**Pull request merged**
