### PR TITLE
#161382360 Users should be able to like and or dislike articles

### PR DESCRIPTION
**Pull request by cdvx**
#### What does this PR do?
Users can like/dislike articles 

#### Description of Task to be completed?
Users can perform `POST`, `GET`, and `PUT` actions on 
`api/articles/<int:pk>/like_status` endpoint
#### How should this be manually tested?
Run server with
`python manage.py runserver`

Use the following actions on endpoint to;
`GET api/articles/<int:pk>/like_status` ==> get article’s like status `POST api/articles/<int:pk>/like_status` ==> like or dislike
`PUT api/articles/<int:pk>/like_status` ==> update like or dislike status of article

`POST` and `PUT` methods accept request bodies of the following format
```
{‘“like_status”: “like”}  
```
To like and,
```
{‘“like_status”: “dislike”}  
```
To dislike

#### Any background context you want to provide?
to test this, one `should` have `PostgreSQL` installed locally and should clone  the repository with

`git clone https://github.com/andela/ah-backend-thor.git`

then create a database called `ah-backend`

make and run migrations
`python manage.py makemigrations`
`python manage.py migrate`

#### What are the relevant pivotal tracker stories?
#161382360

### Screenshots
Posting like
screen shot 2018-11-13 at 18 38 16
Updating like status
screen shot 2018-11-13 at 18 39 08
Getting like status
screen shot 2018-11-13 at 18 42 00
Code refactoring, putting imports in a file
screen shot 2018-11-13 at 18 42 25
Importing imports
screen shot 2018-11-13 at 18 42 42

### CODE REVIEW

**Comment by emukungu** [comment]
LGTM

**Review by bozicschucky — APPROVED** [review]

**Review by johnkegz — APPROVED** [review]

**Comment by malep2007** [comment]
Fix merge conflicts @cdvx

**Comment by malep2007** [comment]
@cdvx build is breaking, why?

**Comment by cdvx** [comment]
> @cdvx build is breaking, why?

@malep2007 The new merges introduced conflicts, which when I fixed online caused my migrations command to fail on travis, so I've rebased and going to push new and updated changes and build should pass then

**Comment by malep2007** [comment]
@cdvx, can we close this then?

**Pull request closed without merging**
